# Netlify Configuration for Our Lady of Fatima Parish Website

[build]
  # Base directory is frontend
  base = "frontend"
  # Build command for the frontend
  command = "npm install && npm run build"
  # Directory to publish (Vite outputs to dist by default)
  publish = "dist"
  # Environment variables for build
  environment = { NODE_VERSION = "18" }

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API proxy rules (if deploying backend separately)
# Uncomment if using serverless functions or external API
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.com/api/:splat"
#   status = 200
#   force = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache control
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Custom error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Environment-specific settings
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm install && npm run build"

[context.branch-deploy]
  command = "npm install && npm run build"
